### ISSUE TITLE
Responsive Design Issue: Lack of Media Queries on Mobile and Tablet Views

### ISSUE THREAD

**Issue by ghost** [isthisLychee/Zoro-Clone#3]
In your Zoro-Clone the desktop view appears well-structured and visually appealing, there seems to be an issue with the responsiveness on mobile and tablet devices.

#Problem:
- On smaller screens like mobiles and tablets, the layout appears distorted and doesn't adapt properly.

#Solution:

- Adding appropriate media queries in the CSS to make adjustments for different screen sizes could greatly improve the responsiveness of the website.

Screenshots:
[Bugs-images.zip](https://github.com/isthisLychee/Zoro-Clone/files/13846384/Bugs-images.zip)

**Comment by isthisLychee** [comment]
Thank You , for your valuable Feedback.
